apiVersion: v1
kind: Service
metadata:
  name: consul-client
  labels:
    name: consul-client
spec:
  ports:
    - name: dashbaord
      port: 80 #8500
      targetPort: 8500
    - name: http
      port: 8500
      targetPort: 8500
    - name: https
      port: 8443
      targetPort: 8443
    - name: serflan-tcp
      protocol: "TCP"
      port: 8301
      targetPort: 8301
    - name: serflan-udp
      protocol: "UDP"
      port: 8301
      targetPort: 8301
    - name: consuldns
      port: 8600
      targetPort: 8600
  selector:
    app: consul-client
